spring.jpa.hibernate.ddl-auto: update
#spring.datasource.url: jdbc:postgresql://localhost:5555/jira-cloud-plugin-db #to connect from the app which is not inside the container
spring.datasource.url: jdbc:postgresql://postgres-db:5432/jira-cloud-plugin-db
spring.datasource.username: user
spring.datasource.password: user
addon.base-url:  https://2c130d5d15df.ngrok.io

logging.level.com.atlassian.connect.spring: DEBUG

spring.thymeleaf.cache: false

application.hash-service-url: http://python-script:5000/hash
#application.hash-service-url: http://127.0.0.1:5000/hash #for python service which is not in Docker